//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace piris.DomainService.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class store_positions
    {
        public int ID { get; set; }
        public string positionName { get; set; }
        public int positionValue { get; set; }
        public string positionType { get; set; }
        public System.DateTime DayOfBuy { get; set; }
        public decimal positionPrice { get; set; }
        public decimal priceCurrency { get; set; }
    }
}
